spring:
  application:
    name: pragmatic-ddd-ecommerce

  datasource:
    url: jdbc:mysql://localhost:3306/ddd-pragmatic
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  session:
    store-type: jdbc
    timeout: 30m
    jdbc:
        initialize-schema: always