spring:
  application:
    name: pragmatic-ddd-ecommerce

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:mysql://localhost:3306/ddd-pragmatic
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  session:
    store-type: jdbc
    timeout: 30m
    jdbc:
      initialize-schema: embedded

logging:
  level:
    com.sakai: TRACE

jwt:
  secret: your-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm
  access-token-expiration: 900000  # 15 minutos em milissegundos
  refresh-token-expiration: 604800000  # 7 dias em milissegundos